### ISSUE TITLE
Creating the error code calls log10(0)

### ISSUE THREAD

**Issue by Tadaboody** [Tadaboody/good_smell#29]
```py
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
  File "/usr/lib/python3.7/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/usr/lib/python3.7/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/lib/python3.7/site-packages/good_smell/flake8_ext.py", line 29, in run
    for warning in warnings
  File "/usr/lib/python3.7/site-packages/good_smell/flake8_ext.py", line 29, in <genexpr>
    for warning in warnings
  File "/usr/lib/python3.7/site-packages/good_smell/flake8_ext.py", line 35, in leading_digit_str
    missing_0s = digits - int(math.log10(num)) - 1
ValueError: math domain error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/flake8", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/lib/python3.7/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/usr/lib/python3.7/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/usr/lib/python3.7/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/usr/lib/python3.7/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/usr/lib/python3.7/site-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 774, in next
    raise value
ValueError: math domain error
```

**Comment by Tadaboody** [comment]
`str.zfill()` does it anyway
